export const artNamespaceFactoryAbi = [
  {
    type: "function",
    name: "createProject",
    stateMutability: "nonpayable",
    inputs: [
      { name: "name", type: "string" },
      { name: "symbol", type: "string" },
      { name: "artistENS", type: "string" },
      { name: "collectionENS", type: "string" },
      { name: "algorithmURI", type: "string" },
      { name: "algorithmHash", type: "bytes32" },
      { name: "maxSupply", type: "uint256" },
      { name: "mintPriceWei", type: "uint256" },
    ],
    outputs: [{ name: "project", type: "address" }],
  },
  {
    type: "function",
    name: "hashCollectionENS",
    stateMutability: "pure",
    inputs: [{ name: "collectionENS", type: "string" }],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "projectForCollectionHash",
    stateMutability: "view",
    inputs: [{ name: "collectionHash", type: "bytes32" }],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "allProjects",
    stateMutability: "view",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "allProjectsLength",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "projectsByArtist",
    stateMutability: "view",
    inputs: [{ name: "artist", type: "address" }],
    outputs: [{ name: "", type: "address[]" }],
  },
  {
    type: "event",
    name: "ProjectCreated",
    inputs: [
      { name: "project", type: "address", indexed: true },
      { name: "artist", type: "address", indexed: true },
      { name: "collectionHash", type: "bytes32", indexed: true },
      { name: "artistENS", type: "string", indexed: false },
      { name: "collectionENS", type: "string", indexed: false },
      { name: "name", type: "string", indexed: false },
      { name: "symbol", type: "string", indexed: false },
      { name: "algorithmURI", type: "string", indexed: false },
      { name: "algorithmHash", type: "bytes32", indexed: false },
      { name: "maxSupply", type: "uint256", indexed: false },
      { name: "mintPriceWei", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
] as const;

export const artNamespaceProjectAbi = [
  {
    type: "function",
    name: "name",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "function",
    name: "symbol",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "function",
    name: "artistENS",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "function",
    name: "collectionENS",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "function",
    name: "mintArtwork",
    stateMutability: "payable",
    inputs: [
      { name: "to", type: "address" },
      { name: "metadataURI", type: "string" },
      { name: "uniquenessHash", type: "bytes32" },
    ],
    outputs: [{ name: "tokenId", type: "uint256" }],
  },
  {
    type: "function",
    name: "configureEnsSubnames",
    stateMutability: "nonpayable",
    inputs: [
      { name: "registrar", type: "address" },
      { name: "parentNode", type: "bytes32" },
      { name: "resolver", type: "address" },
      { name: "ttl", type: "uint64" },
      { name: "fuses", type: "uint32" },
      { name: "expiry", type: "uint64" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "configureEnsV2Subnames",
    stateMutability: "nonpayable",
    inputs: [
      { name: "registry", type: "address" },
      { name: "resolver", type: "address" },
      { name: "expiry", type: "uint64" },
      { name: "roleBitmap", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "withdraw",
    stateMutability: "nonpayable",
    inputs: [{ name: "recipient", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "nextTokenId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "nextArtworkENS",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "function",
    name: "artworkENSFor",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "function",
    name: "artworkLabel",
    stateMutability: "pure",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "function",
    name: "mintPriceWei",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "ensSubnameRegistrar",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "ensParentNode",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "ensResolver",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "ensSubnameMode",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
  },
  {
    type: "function",
    name: "ensSubnameRoleBitmap",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "owner",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "ownerOf",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "maxSupply",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "algorithmURI",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "function",
    name: "algorithmHash",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "tokenURI",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "function",
    name: "tokenENS",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "event",
    name: "ArtworkMinted",
    inputs: [
      { name: "tokenId", type: "uint256", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "artworkENS", type: "string", indexed: false },
      { name: "metadataURI", type: "string", indexed: false },
      { name: "uniquenessHash", type: "bytes32", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "EnsSubnamesConfigured",
    inputs: [
      { name: "registrar", type: "address", indexed: true },
      { name: "parentNode", type: "bytes32", indexed: true },
      { name: "resolver", type: "address", indexed: true },
      { name: "ttl", type: "uint64", indexed: false },
      { name: "fuses", type: "uint32", indexed: false },
      { name: "expiry", type: "uint64", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "EnsV2SubnamesConfigured",
    inputs: [
      { name: "registry", type: "address", indexed: true },
      { name: "resolver", type: "address", indexed: true },
      { name: "expiry", type: "uint64", indexed: false },
      { name: "roleBitmap", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ArtworkSubnameCreated",
    inputs: [
      { name: "tokenId", type: "uint256", indexed: true },
      { name: "label", type: "string", indexed: false },
      { name: "artworkENS", type: "string", indexed: false },
      { name: "owner", type: "address", indexed: true },
    ],
    anonymous: false,
  },
] as const;
